2020-04-22 09:42:55,182 ERROR 15160 [-/::1/-/5086ms GET /news] nodejs.ConnectionTimeoutError: Connect timeout for 5000ms, GET https://hacker-news.firebaseio.com/v0/topstories.json -2 (connected: false, keepalive socket: false, agent status: {"createSocketCount":3,"createSocketErrorCount":0,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
headers: {}
    at Timeout._onTimeout (C:\Users\zhang\Desktop\egg\node_modules\_urllib@2.34.2@urllib\lib\urllib.js:926:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ConnectionTimeoutError"
requestId: 3
data: undefined
path: "/v0/topstories.json?orderBy=%22%24key%22&startAt=%220%22&endAt=%224%22"
status: -2
headers: {}
res: {"status":-2,"statusCode":-2,"statusMessage":null,"headers":{},"size":0,"aborted":false,"rt":5040,"keepAliveSocket":false,"requestUrls":["https://hacker-news.firebaseio.com/v0/topstories.json"],"timing":null,"remoteAddress":"35.201.97.85","remotePort":"","socketHandledRequests":1,"socketHandledResponses":0}
pid: 15160
hostname: DESKTOP-1JNFRSL

2020-04-23 11:14:19,465 ERROR 12496 [-/::1/-/2ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:7:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 12496
hostname: DESKTOP-1JNFRSL

2020-04-23 11:22:24,640 ERROR 4956 [-/::1/-/30ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:8:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 4956
hostname: DESKTOP-1JNFRSL

2020-04-23 11:23:57,046 ERROR 14748 [-/::1/-/20ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:8:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 14748
hostname: DESKTOP-1JNFRSL

2020-04-23 11:24:51,768 ERROR 13260 [-/::1/-/25ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:8:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 13260
hostname: DESKTOP-1JNFRSL

2020-04-23 11:24:53,255 ERROR 13260 [-/::1/-/7ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:8:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 13260
hostname: DESKTOP-1JNFRSL

2020-04-23 11:24:54,642 ERROR 13260 [-/::1/-/10ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:8:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 13260
hostname: DESKTOP-1JNFRSL

2020-04-23 11:25:10,933 ERROR 17448 [-/::1/-/26ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:8:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 17448
hostname: DESKTOP-1JNFRSL

2020-04-23 11:25:12,373 ERROR 17448 [-/::1/-/26ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:8:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 17448
hostname: DESKTOP-1JNFRSL

2020-04-23 11:25:12,964 ERROR 17448 [-/::1/-/12ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:8:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 17448
hostname: DESKTOP-1JNFRSL

2020-04-23 11:25:32,023 ERROR 17448 [-/::1/-/11ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:8:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 17448
hostname: DESKTOP-1JNFRSL

2020-04-23 11:25:34,525 ERROR 15052 [-/::1/-/10ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:7:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 15052
hostname: DESKTOP-1JNFRSL

2020-04-23 11:25:53,511 ERROR 15052 [-/::1/-/2ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:7:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 15052
hostname: DESKTOP-1JNFRSL

2020-04-23 11:25:55,738 ERROR 9312 [-/::1/-/9ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:7:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 9312
hostname: DESKTOP-1JNFRSL

2020-04-23 11:26:04,836 ERROR 9312 [-/::1/-/1ms GET /user] nodejs.TypeError: ctx.service.user.find is not a function
    at UserController.user (C:\Users\zhang\Desktop\egg\app\controller\user.js:7:41)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\zhang\Desktop\egg\node_modules\_egg-core@4.17.4@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\zhang\Desktop\egg\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\zhang\Desktop\egg\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12

pid: 9312
hostname: DESKTOP-1JNFRSL

2020-04-23 11:27:02,657 ERROR 9488 [-/::1/-/17ms GET /user] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table '1112.users' doesn't exist
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `users` WHERE `id` = 11 LIMIT 0, 1
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table '1112.users' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT * FROM `users` WHERE `id` = 11 LIMIT 0, 1"
name: "ER_NO_SUCH_TABLEError"
pid: 9488
hostname: DESKTOP-1JNFRSL

2020-04-23 11:27:09,076 ERROR 9488 [-/::1/-/2ms GET /user] nodejs.ER_NO_SUCH_TABLEError: ER_NO_SUCH_TABLE: Table '1112.users' doesn't exist
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `users` WHERE `id` = 11 LIMIT 0, 1
code: "ER_NO_SUCH_TABLE"
errno: 1146
sqlMessage: "Table '1112.users' doesn't exist"
sqlState: "42S02"
index: 0
sql: "SELECT * FROM `users` WHERE `id` = 11 LIMIT 0, 1"
name: "ER_NO_SUCH_TABLEError"
pid: 9488
hostname: DESKTOP-1JNFRSL

2020-04-23 16:48:44,041 ERROR 11248 [-/::1/-/11ms GET /login] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1"
name: "ER_BAD_FIELD_ERRORError"
pid: 11248
hostname: DESKTOP-1JNFRSL

2020-04-23 16:53:06,071 ERROR 11248 [-/::1/-/9ms GET /login] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1"
name: "ER_BAD_FIELD_ERRORError"
pid: 11248
hostname: DESKTOP-1JNFRSL

2020-04-23 16:54:39,406 ERROR 11248 [-/::1/-/4ms GET /login] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 11248
hostname: DESKTOP-1JNFRSL

2020-04-23 16:55:48,729 ERROR 11248 [-/::1/-/2ms GET /login] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 11248
hostname: DESKTOP-1JNFRSL

2020-04-23 16:56:42,121 ERROR 11248 [-/::1/-/3ms GET /login?name=cpic&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 11248
hostname: DESKTOP-1JNFRSL

2020-04-23 16:58:13,772 ERROR 7900 [-/::1/-/38ms GET /login?name=root&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 7900
hostname: DESKTOP-1JNFRSL

2020-04-23 16:58:53,402 ERROR 3956 [-/::1/-/22ms GET /login?name=root&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` IS NULL AND `password` IS NULL LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 3956
hostname: DESKTOP-1JNFRSL

2020-04-23 17:12:51,203 ERROR 18072 [-/::1/-/21ms GET /login?name=cpic&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` = 'cpic' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` = 'cpic' AND `password` = '123456' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18072
hostname: DESKTOP-1JNFRSL

2020-04-23 17:12:58,896 ERROR 18072 [-/::1/-/2ms GET /login?name=root&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` = 'root' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` = 'root' AND `password` = '123456' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 18072
hostname: DESKTOP-1JNFRSL

2020-04-23 17:13:36,462 ERROR 5740 [-/::1/-/25ms GET /login?name=root&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` = 'root' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` = 'root' AND `password` = '123456' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 5740
hostname: DESKTOP-1JNFRSL

2020-04-23 17:13:37,328 ERROR 5740 [-/::1/-/3ms GET /login?name=root&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` = 'root' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` = 'root' AND `password` = '123456' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 5740
hostname: DESKTOP-1JNFRSL

2020-04-23 17:13:37,532 ERROR 5740 [-/::1/-/2ms GET /login?name=root&password=123456] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    --------------------
    at Pool.query (C:\Users\zhang\Desktop\egg\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\zhang\Desktop\egg\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\client.js:34:20)
    at RDSClient.proto.query (C:\Users\zhang\Desktop\egg\node_modules\_ali-rds@3.3.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\zhang\Desktop\egg\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT * FROM `user` WHERE `name` = 'root' AND `password` = '123456' LIMIT 0, 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `user` WHERE `name` = 'root' AND `password` = '123456' LIMIT 0, 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 5740
hostname: DESKTOP-1JNFRSL

